vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: '%kernel.project_dir%/public/assets/uploads'  # Chemin complet vers le répertoire d'upload
            upload_destination: '%kernel.project_dir%/public/assets/uploads'  # Chemin complet vers le répertoire d'upload